/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVulnerable__factory } from "./IVulnerable__factory";
export { TxOriginAttacker__factory } from "./TxOriginAttacker__factory";
