/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVulnerable,
  IVulnerableInterface,
} from "../../../../contracts/tx-origin/TxOriginAttacker.sol/IVulnerable";

const _abi = [
  {
    inputs: [],
    name: "withdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVulnerable__factory {
  static readonly abi = _abi;
  static createInterface(): IVulnerableInterface {
    return new Interface(_abi) as IVulnerableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVulnerable {
    return new Contract(address, _abi, runner) as unknown as IVulnerable;
  }
}
