/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVulnerableBankV2,
  IVulnerableBankV2Interface,
} from "../../ReentrancyAttackerV2.sol/IVulnerableBankV2";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVulnerableBankV2__factory {
  static readonly abi = _abi;
  static createInterface(): IVulnerableBankV2Interface {
    return new Interface(_abi) as IVulnerableBankV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVulnerableBankV2 {
    return new Contract(address, _abi, runner) as unknown as IVulnerableBankV2;
  }
}
