/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVulnerableBank,
  IVulnerableBankInterface,
} from "../../ReentrancyAttacker.sol/IVulnerableBank";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVulnerableBank__factory {
  static readonly abi = _abi;
  static createInterface(): IVulnerableBankInterface {
    return new Interface(_abi) as IVulnerableBankInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVulnerableBank {
    return new Contract(address, _abi, runner) as unknown as IVulnerableBank;
  }
}
