/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReentrancyAttackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attack"
      | "attackAmount"
      | "attackerBalance"
      | "bank"
      | "loops"
      | "maxLoops"
      | "setMaxLoops"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "attack", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attackAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attackerBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bank", values?: undefined): string;
  encodeFunctionData(functionFragment: "loops", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxLoops", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxLoops",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackerBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loops", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxLoops", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxLoops",
    data: BytesLike
  ): Result;
}

export interface ReentrancyAttacker extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrancyAttacker;
  waitForDeployment(): Promise<this>;

  interface: ReentrancyAttackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attack: TypedContractMethod<[], [void], "payable">;

  attackAmount: TypedContractMethod<[], [bigint], "view">;

  attackerBalance: TypedContractMethod<[], [bigint], "view">;

  bank: TypedContractMethod<[], [string], "view">;

  loops: TypedContractMethod<[], [bigint], "view">;

  maxLoops: TypedContractMethod<[], [bigint], "view">;

  setMaxLoops: TypedContractMethod<
    [_maxLoops: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "attackAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attackerBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bank"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "loops"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxLoops"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMaxLoops"
  ): TypedContractMethod<[_maxLoops: BigNumberish], [void], "nonpayable">;

  filters: {};
}
