/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as txOriginAttackerSol from "./TxOriginAttacker.sol";
export type { txOriginAttackerSol };
export type { SafeTxOrigin } from "./SafeTxOrigin";
export type { VulnerableTxOrigin } from "./VulnerableTxOrigin";
