/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SafeGame__factory } from "./SafeGame__factory";
export { VulnerableGame__factory } from "./VulnerableGame__factory";
