/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  VulnerableGame,
  VulnerableGameInterface,
} from "../../../contracts/front-running/VulnerableGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "number",
        type: "uint256",
      },
    ],
    name: "guess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "winner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102eb806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639189fec11461003b578063dfbf53ae14610057575b600080fd5b610055600480360381019061005091906101af565b610075565b005b61005f610150565b60405161006c919061021d565b60405180910390f35b600073ffffffffffffffffffffffffffffffffffffffff1660008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1614610104576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100fb90610295565b60405180910390fd5b602a810361014d57336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600080fd5b6000819050919050565b61018c81610179565b811461019757600080fd5b50565b6000813590506101a981610183565b92915050565b6000602082840312156101c5576101c4610174565b5b60006101d38482850161019a565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610207826101dc565b9050919050565b610217816101fc565b82525050565b6000602082019050610232600083018461020e565b92915050565b600082825260208201905092915050565b7f616c726561647920776f6e000000000000000000000000000000000000000000600082015250565b600061027f600b83610238565b915061028a82610249565b602082019050919050565b600060208201905081810360008301526102ae81610272565b905091905056fea2646970667358221220bf68c8226bfb394624709d510044ee390f9b4c0f4654deca24ec5bac94d286c564736f6c63430008140033";

type VulnerableGameConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VulnerableGameConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VulnerableGame__factory extends ContractFactory {
  constructor(...args: VulnerableGameConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VulnerableGame & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VulnerableGame__factory {
    return super.connect(runner) as VulnerableGame__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VulnerableGameInterface {
    return new Interface(_abi) as VulnerableGameInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VulnerableGame {
    return new Contract(address, _abi, runner) as unknown as VulnerableGame;
  }
}
