/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVulnerableBankV2 } from "./IVulnerableBankV2";
export type { ReentrancyAttackerV2 } from "./ReentrancyAttackerV2";
