/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SafeVault__factory } from "./SafeVault__factory";
export { VulnerableVault__factory } from "./VulnerableVault__factory";
