/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  VulnerableVault,
  VulnerableVaultInterface,
} from "../../../contracts/access-control/VulnerableVault";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061035a806100606000396000f3fe6080604052600436106100385760003560e01c806313af403514610044578063853828b61461006d5780638da5cb5b146100845761003f565b3661003f57005b600080fd5b34801561005057600080fd5b5061006b60048036038101906100669190610250565b6100af565b005b34801561007957600080fd5b506100826100f2565b005b34801561009057600080fd5b506100996101c9565b6040516100a6919061028c565b60405180910390f35b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610180576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161017790610304565b60405180910390fd5b3373ffffffffffffffffffffffffffffffffffffffff166108fc479081150290604051600060405180830381858888f193505050501580156101c6573d6000803e3d6000fd5b50565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061021d826101f2565b9050919050565b61022d81610212565b811461023857600080fd5b50565b60008135905061024a81610224565b92915050565b600060208284031215610266576102656101ed565b5b60006102748482850161023b565b91505092915050565b61028681610212565b82525050565b60006020820190506102a1600083018461027d565b92915050565b600082825260208201905092915050565b7f6e6f74206f776e65720000000000000000000000000000000000000000000000600082015250565b60006102ee6009836102a7565b91506102f9826102b8565b602082019050919050565b6000602082019050818103600083015261031d816102e1565b905091905056fea2646970667358221220ff4dbea991760714972cfdb5da8b91ce52b0e89021da6c664e900bbab6a77ddb64736f6c63430008140033";

type VulnerableVaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VulnerableVaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VulnerableVault__factory extends ContractFactory {
  constructor(...args: VulnerableVaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VulnerableVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VulnerableVault__factory {
    return super.connect(runner) as VulnerableVault__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VulnerableVaultInterface {
    return new Interface(_abi) as VulnerableVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VulnerableVault {
    return new Contract(address, _abi, runner) as unknown as VulnerableVault;
  }
}
