/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as txOriginAttackerSol from "./TxOriginAttacker.sol";
export { SafeTxOrigin__factory } from "./SafeTxOrigin__factory";
export { VulnerableTxOrigin__factory } from "./VulnerableTxOrigin__factory";
