/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SafeVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeVault__factory>;
    getContractFactory(
      name: "VulnerableVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VulnerableVault__factory>;
    getContractFactory(
      name: "IVulnerableBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVulnerableBank__factory>;
    getContractFactory(
      name: "ReentrancyAttacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyAttacker__factory>;
    getContractFactory(
      name: "IVulnerableBankV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVulnerableBankV2__factory>;
    getContractFactory(
      name: "ReentrancyAttackerV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyAttackerV2__factory>;
    getContractFactory(
      name: "SafeBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeBank__factory>;
    getContractFactory(
      name: "SafeBankV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeBankV2__factory>;
    getContractFactory(
      name: "VulnerableBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VulnerableBank__factory>;
    getContractFactory(
      name: "VulnerableBankV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VulnerableBankV2__factory>;
    getContractFactory(
      name: "SafeTxOrigin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeTxOrigin__factory>;
    getContractFactory(
      name: "IVulnerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVulnerable__factory>;
    getContractFactory(
      name: "TxOriginAttacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TxOriginAttacker__factory>;
    getContractFactory(
      name: "VulnerableTxOrigin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VulnerableTxOrigin__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SafeVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeVault>;
    getContractAt(
      name: "VulnerableVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VulnerableVault>;
    getContractAt(
      name: "IVulnerableBank",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVulnerableBank>;
    getContractAt(
      name: "ReentrancyAttacker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyAttacker>;
    getContractAt(
      name: "IVulnerableBankV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVulnerableBankV2>;
    getContractAt(
      name: "ReentrancyAttackerV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyAttackerV2>;
    getContractAt(
      name: "SafeBank",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeBank>;
    getContractAt(
      name: "SafeBankV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeBankV2>;
    getContractAt(
      name: "VulnerableBank",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VulnerableBank>;
    getContractAt(
      name: "VulnerableBankV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VulnerableBankV2>;
    getContractAt(
      name: "SafeTxOrigin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeTxOrigin>;
    getContractAt(
      name: "IVulnerable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVulnerable>;
    getContractAt(
      name: "TxOriginAttacker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TxOriginAttacker>;
    getContractAt(
      name: "VulnerableTxOrigin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VulnerableTxOrigin>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeVault>;
    deployContract(
      name: "VulnerableVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableVault>;
    deployContract(
      name: "IVulnerableBank",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerableBank>;
    deployContract(
      name: "ReentrancyAttacker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyAttacker>;
    deployContract(
      name: "IVulnerableBankV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerableBankV2>;
    deployContract(
      name: "ReentrancyAttackerV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyAttackerV2>;
    deployContract(
      name: "SafeBank",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeBank>;
    deployContract(
      name: "SafeBankV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeBankV2>;
    deployContract(
      name: "VulnerableBank",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableBank>;
    deployContract(
      name: "VulnerableBankV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableBankV2>;
    deployContract(
      name: "SafeTxOrigin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeTxOrigin>;
    deployContract(
      name: "IVulnerable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerable>;
    deployContract(
      name: "TxOriginAttacker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TxOriginAttacker>;
    deployContract(
      name: "VulnerableTxOrigin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableTxOrigin>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SafeVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeVault>;
    deployContract(
      name: "VulnerableVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableVault>;
    deployContract(
      name: "IVulnerableBank",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerableBank>;
    deployContract(
      name: "ReentrancyAttacker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyAttacker>;
    deployContract(
      name: "IVulnerableBankV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerableBankV2>;
    deployContract(
      name: "ReentrancyAttackerV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyAttackerV2>;
    deployContract(
      name: "SafeBank",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeBank>;
    deployContract(
      name: "SafeBankV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeBankV2>;
    deployContract(
      name: "VulnerableBank",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableBank>;
    deployContract(
      name: "VulnerableBankV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableBankV2>;
    deployContract(
      name: "SafeTxOrigin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeTxOrigin>;
    deployContract(
      name: "IVulnerable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVulnerable>;
    deployContract(
      name: "TxOriginAttacker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TxOriginAttacker>;
    deployContract(
      name: "VulnerableTxOrigin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VulnerableTxOrigin>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
