/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVulnerable } from "./IVulnerable";
export type { TxOriginAttacker } from "./TxOriginAttacker";
